### ISSUE TITLE
capm3-controller-manager invalid memory address error

### ISSUE THREAD

**Issue by Xenwar** [metal3-io/cluster-api-provider-metal3#22]
**What steps did you take and what happened:**
Provision and de-provision a control plane machine multiple times.
It goes to CrashLoopBackOff with invalid memory address error

full log is added as a comment
**What did you expect to happen:**
A success or a graceful failure.

**Anything else you would like to add:**
Regardless of the cause, please do focus on fixing the ` invalid memory address error`

This makes the environment not usable. One needs to run `make clean` and `make` again.
**Environment:**

- Cluster-api version: v1alpha3
- CAPBM version: v1alpha3
- Minikube version: v1.8.2
- environment: metal3-dev-env
- Kubernetes version: 1.17.0

/kind bug

**Comment by Xenwar** [comment]
```
I0318 07:44:12.413056       1 metal3machine_manager.go:378] controllers/Metal3Machine/Metal3Machine-controller "msg"="Deleting bare metal machine" "cluster"="test1" "machine"="test1-controlplane-8zxdr" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-controlplane-77dww"} "metal3machine"="test1-controlplane-77dww"
E0318 07:44:12.413983       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 312 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1525f00, 0x24c6920)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1525f00, 0x24c6920)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/metal3-io/cluster-api-provider-metal3/baremetal.(*MachineManager).Delete(0xc00045e640, 0x1916b60, 0xc000056218, 0x13a641e, 0x1609980)
	/workspace/baremetal/metal3machine_manager.go:477 +0x6bb
github.com/metal3-io/cluster-api-provider-metal3/controllers.(*Metal3MachineReconciler).reconcileDelete(0xc0006ee340, 0x1916b60, 0xc000056218, 0x1938800, 0xc00045e640, 0x1924f20, 0xc0006d0e40, 0x1938800, 0xc00045e640)
	/workspace/controllers/metal3machine_controller.go:214 +0x49
github.com/metal3-io/cluster-api-provider-metal3/controllers.(*Metal3MachineReconciler).Reconcile(0xc0006ee340, 0xc000453ba0, 0x6, 0xc00072e5a0, 0x18, 0xc000814c00, 0x0, 0x0, 0x0)
	/workspace/controllers/metal3machine_controller.go:156 +0xa1c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0005ba480, 0x1579260, 0xc000562020, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0005ba480, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0005ba480)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00022a240)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00022a240, 0x3b9aca00, 0x0, 0x1, 0xc000089e60)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00022a240, 0x3b9aca00, 0xc000089e60)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:193 +0x328
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x13a076b]

goroutine 312 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1525f00, 0x24c6920)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/metal3-io/cluster-api-provider-metal3/baremetal.(*MachineManager).Delete(0xc00045e640, 0x1916b60, 0xc000056218, 0x13a641e, 0x1609980)
	/workspace/baremetal/metal3machine_manager.go:477 +0x6bb
github.com/metal3-io/cluster-api-provider-metal3/controllers.(*Metal3MachineReconciler).reconcileDelete(0xc0006ee340, 0x1916b60, 0xc000056218, 0x1938800, 0xc00045e640, 0x1924f20, 0xc0006d0e40, 0x1938800, 0xc00045e640)
	/workspace/controllers/metal3machine_controller.go:214 +0x49
github.com/metal3-io/cluster-api-provider-metal3/controllers.(*Metal3MachineReconciler).Reconcile(0xc0006ee340, 0xc000453ba0, 0x6, 0xc00072e5a0, 0x18, 0xc000814c00, 0x0, 0x0, 0x0)
	/workspace/controllers/metal3machine_controller.go:156 +0xa1c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0005ba480, 0x1579260, 0xc000562020, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0005ba480, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0005ba480)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00022a240)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00022a240, 0x3b9aca00, 0x0, 0x1, 0xc000089e60)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00022a240, 0x3b9aca00, 0xc000089e60)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:193 +0x328

```

**Comment by Jaakko-Os** [comment]
did the provision and de-provision control plane machine procedure succeed once or few times before the crash?

**Comment by Xenwar** [comment]
The first time it was success. Then it is not predictable. But, the more you repeat the more likely you will see the error.

**Comment by maelk** [comment]
The core problem, is that in the Delete function, we try to access the BMH namespace, while the BMH might be nil. We need to fix the deletion steps order.

**Comment by maelk** [comment]
working on it
