### ISSUE TITLE
Metal3DataTemplate DNS overrides are not applied

### ISSUE THREAD

**Issue by andfasano** [metal3-io/cluster-api-provider-metal3#339]
**What steps did you take and what happened:**
I tried to provision a new cluster using a fresh metal3-dev-env and specifying a custom DNS.

```
### config_afasano.sh
export KUBERNETES_VERSION="v1.22.2"
export NUM_NODES=4
```
```
1. $ make
2. $ ./scripts/provision/cluster.sh
3. $ ./scripts/provision/controlplane.sh
4. $ ./scripts/provision/workers.sh
```
DNS was configured by changing the default `8.8.8.8` value in the [metal3datatemplate-template.yaml](https://github.com/metal3-io/metal3-dev-env/blob/35cb4f4165e0546e3e63b18a647447151223076e/vm-setup/roles/v1aX_integration_test/templates/metal3datatemplate-template.yaml#L66) file to a custom value.

On step 3, the controlplane machine remained stuck in Phase `Provisioning` and the target cluster wasn't deployed at all.

**What did you expect to happen:**
To provision correctly the target cluster

**Anything else you would like to add:**
Further inspection in the target cluster controlplane node revelead that the `kubeadm` (triggered during cloud-init) failed to to download the required cluster images:

```
 [preflight] Pulling images required for setting up a Kubernetes cluster
 [preflight] This might take a minute or two, depending on the speed of your internet connection
 [preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
 error execution phase preflight: [preflight] Some fatal errors occurred:
         [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.22.0: output: time="2021-10-14T11:51:07Z" level=fatal msg="pulling image: rpc>
 , error: exit status 1
         [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.22.0: output: time="2021-10-14T11:56:07Z" level=fatal msg="pulling i>
 , error: exit status 1
         [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.22.0: output: time="2021-10-14T12:01:08Z" level=fatal msg="pulling image: rpc>
 , error: exit status 1
         [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.22.0: output: time="2021-10-14T12:06:08Z" level=fatal msg="pulling image: rpc err>
 , error: exit status 1
         [ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.5: output: time="2021-10-14T12:11:08Z" level=fatal msg="pulling image: rpc error: code >
 , error: exit status 1
         [ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.5.0-0: output: time="2021-10-14T12:16:08Z" level=fatal msg="pulling image: rpc error: co>
 , error: exit status 1
         [ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns/coredns:v1.8.4: output: time="2021-10-14T12:21:08Z" level=fatal msg="pulling image: rpc>
 , error: exit status 1
 [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
 To see the stack trace of this error execute with --v=5 or higher
 cp: cannot stat '/etc/kubernetes/admin.conf': No such file or directory
 chown: cannot access '/home/metal3/.kube/config': No such file or directory
 Cloud-init v. 21.1-7.el8 running 'modules:final' at Thu, 14 Oct 2021 11:45:25 +0000. Up 14.92 seconds.
```
This prevented the controlplane to bootstrap properly.

Checking `/etc/resolv.conf` revealed that its content was not modified. By looking previously at the logs, it appears that cloud-init wasn't able effectively to change it during the init-local stage:

```
failed run of stage init-local                                
------------------------------------------------------------  
Traceback (most recent call last):                            
  File "/usr/lib/python3.6/site-packages/cloudinit/cmd/main.py", line 652, in status_wrapper
    ret = functor(name, args)                                 
  File "/usr/lib/python3.6/site-packages/cloudinit/cmd/main.py", line 361, in main_init
    init.apply_network_config(bring_up=bool(mode != sources.DSMODE_LOCAL))
  File "/usr/lib/python3.6/site-packages/cloudinit/stages.py", line 735, in apply_network_config
    return self.distro.apply_network_config(netcfg, bring_up=bring_up)                                                                                                                                  
  File "/usr/lib/python3.6/site-packages/cloudinit/distros/__init__.py", line 206, in apply_network_config                                                                                              
    dev_names = self._write_network_config(netconfig)                                                                                                                                                   
  File "/usr/lib/python3.6/site-packages/cloudinit/distros/rhel.py", line 66, in _write_network_config                                                                                                  
    return self._supported_write_network_config(netconfig)                                                                                                                                              
  File "/usr/lib/python3.6/site-packages/cloudinit/distros/__init__.py", line 121, in _supported_write_network_config                                                                                   
    renderer.render_network_config(network_config)
  File "/usr/lib/python3.6/site-packages/cloudinit/net/renderer.py", line 56, in render_network_config
    templates=templates, target=target)                       
  File "/usr/lib/python3.6/site-packages/cloudinit/net/sysconfig.py", line 909, in render_network_state
    util.write_file(dns_path, resolv_content, file_mode)                                                                                                                                                
  File "/usr/lib/python3.6/site-packages/cloudinit/util.py", line 1926, in write_file
    with open(filename, omode) as fh:                                                          
PermissionError: [Errno 1] Operation not permitted: '/etc/resolv.conf'                       
------------------------------------------------------------
```
The `/etc/resolv.conf` had the immutable flag `i` set, and this prevented cloud-init to modify it properly. Very likely, it seems that (at least on the current Centos8 image) the DNS settings were never been applied, and the image pre-existing `resolv.conf` content was used (which incidentally was pointing to `8.8.8.8`).

Thanks to @fmuyassarov for the help in troubleshooting this issue

**Environment:**

- Cluster-api version: 0.4.4
- Cluster-api-provider-metal3 version: 0.5.1
- Environment (metal3-dev-env or other): metal3-dev-env
- Kubernetes version: (use `kubectl version`): 1.22.2

**Workaround**

As a temporary workaround, I modified the `preKubeadmCommands` in both [cluter-template-controlplane-kubeadm-config-centos.yaml](https://github.com/metal3-io/metal3-dev-env/blob/35cb4f4165e0546e3e63b18a647447151223076e/vm-setup/roles/v1aX_integration_test/templates/cluster-template-controlplane-kubeadm-config-centos.yaml#L2) and [cluster-template-workers-kubeadm-config-centos.yaml](https://github.com/metal3-io/metal3-dev-env/blob/35cb4f4165e0546e3e63b18a647447151223076e/vm-setup/roles/v1aX_integration_test/templates/cluster-template-workers-kubeadm-config-centos.yaml#L2) to change directly the `/etc/resolv.conf`

/kind bug

**Comment by furkatgofurov7** [comment]
@andfasano hi! We have seen something similar in https://github.com/metal3-io/metal3-dev-env/issues/895 and [this](https://github.com/metal3-io/metal3-dev-env/issues/895#issuecomment-1006808117) helped to work around it.
